# Site settings
site: kangnurrohman
title: Kang Nur
keywords: kangnurrohman, blog
description: >-
  suka main, suka njajan
lang: id
timezone: Asia/Jakarta
repo: https://github.com/kangnurrohman # site repo [optional]
google_verify: KiDrA9nVZ1mhCQ9V-KW7sbO4OH5qnbgh8cTgztXbwag # Put your Google Verification here
google_analytics: G-NDW1FJZQ74 # Put your Google Analytics code
discus-identifier: kangnurrohman

# Author settings
author:
  name: Kang Nur
  bio: Suka main, njajan, dan data
  picture: assets/images/profile.jpg
  github: kangnurrohman # github username
  twitter: kangnurrohman # twitter username
  facebook: kangnurrohman # facebook username
  instagram: kangnurrohman # instagram username
  linkedin: kangnurrohman # linkedin username
  email: ainurrohman869@email.com # email adress
  kaggle: ainurrohmanbwx # email adress

# URL settings
url: "https://kangnurrohman.github.io" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false



