# Site settings
site: kangnurrohman
title: Kang Nur
keywords: Data Analyst, Data Analytics, Data Science, Data Scientist, Machine Learning, Deep Learning, Artificial Intelligence, Matematika, Budaya, Kuliner
description: >-
  Sebuah blog pribadi berisi tentang Ilmu Komputer khususnya data science, budaya banyuwangi, travelling, dan kuliner.
lang: id
timezone: Asia/Jakarta
repo: https://github.com/kangnurrohman.github.io # site repo [optional]
google_verify: google-site-verification=LVWbsUypSRWd572qyjH8JMCJr79CSQTUp_Yz96wM1GU # Put your Google Verification here
google_analytics: G-NDW1FJZQ74 # Put your Google Analytics code
discus-identifier: kangnurrohman

# Author settings
author:
  name: Kang Nur
  bio: Suka main, njajan, dan data
  picture: assets/images/profile.jpg
  github: kangnurrohman # github username
  twitter: kangnurrohman # twitter username
  facebook: kangnurrohman # facebook username
  instagram: kangnurrohman # instagram username
  linkedin: kangnurrohman # linkedin username
  email: ainurrohman869@email.com # email adress
  kaggle: ainurrohmanbwx # email adress

# URL settings
url: "https://kangnur.my.id" # Domain Name of host. [username].github.io for github pages
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false



